Update Portable GIT for windows to version 2.47.0.2

diff --git a/dependencies/windows_amd64/PortableGit/usr/bin/getemojis b/dependencies/windows_amd64/PortableGit/usr/bin/getemojis
--- a/dependencies/windows_amd64/PortableGit/usr/bin/getemojis
+++ b/dependencies/windows_amd64/PortableGit/usr/bin/getemojis
@@ -5,10 +5,13 @@ trace () {
 	true
 }
 
+wgetfirst=false
+#wgetfirst=true
+
 case "$1" in
 -sh)	postproc=cat
 	shift;;
-*)	postproc=sh;;
+*)	postproc=bash;;
 esac
 
 case `basename "$PWD"` in
@@ -19,14 +22,29 @@ mintty)
 	exit;;
 esac
 
-emojisurl0=http://www.unicode.org/emoji/charts/full-emoji-list.html
-emojisurl1=http://www.unicode.org/emoji/charts/full-emoji-modifiers.html
+emojisurl0=https://www.unicode.org/emoji/charts/full-emoji-list.html
+emojisurl1=https://www.unicode.org/emoji/charts/full-emoji-modifiers.html
 
 download () {
-	if type curl
-	then	curl -RO -z `basename $1` $1
-	else	wget -N -t 1 $1
-	fi
+	if $wgetfirst
+	then	wget -N -t 1 "$1"
+	elif type curl
+	then	# prefer curl because it works better behind proxies
+		if [ -f `basename "$1"` ]
+		then	curl -RO -z `basename "$1"` "$1"
+		else	# avoid "Warning: Illegal date format for -z"
+			curl -RO "$1"
+		fi
+	else	wget -N -t 1 "$1"
+	fi ||
+	(echo "[41;30mFILE: $1[m" >&2
+	 echo "[41;30mERROR: download failed, file incomplete[m" >&2
+	 if [ -f `basename "$1"` ]
+	 then	# enforce fresh download next time
+		touch -d 1970-01-01 `basename "$1"`
+	 fi
+	 return 9
+	)
 }
 
 case "$1" in
@@ -37,8 +55,10 @@ case "$1" in
 	echo "	$emojisurl0" >&2
 	echo "	$emojisurl1" >&2
 	echo "for the selected emoji style sets, or (if none selected) all of them:" >&2
-	echo "	apple google facebook windows twitter emojione samsung" >&2
+	echo "	google" >&2
 	echo "and always extracts common emoji graphics." >&2
+	echo "Other styles are no longer provided at unicode.org:" >&2
+	echo "	[apple facebook windows twitter emojione samsung]" >&2
 	echo >&2
 	echo "Options:" >&2
 	echo "	-d	Download the chart files" >&2
@@ -46,12 +66,16 @@ case "$1" in
 	echo >&2
 	echo "Warning: with all styles selected, this may take a while." >&2
 	echo >&2
-	echo "Note: for direct deployment, first go into subdirectory 'emojis' of one of the" >&2
-	echo "mintty config directories:" >&2
-	echo '  ~/.mintty' >&2
-	echo '  ~/.config/mintty' >&2
-	echo '  $APPDATA/mintty' >&2
-	echo '  /usr/share/mintty' >&2
+	if [ `uname` = "Linux" ] && type wslpath 2> /dev/null 1>&2
+	then	echo "Note: for direct deployment from WSL, first go into the common config directory:" >&2
+		echo '  cd `wslpath "$APPDATA/mintty/emojis"` || cd `wslpath "$APPDATA/wsltty/emojis"`' >&2
+	else	echo "Note: for direct deployment, first go into subdirectory 'emojis' of one of the" >&2
+		echo "mintty config directories:" >&2
+		echo '  ~/.mintty' >&2
+		echo '  ~/.config/mintty' >&2
+		echo '  $APPDATA/mintty' >&2
+		echo '  /usr/share/mintty' >&2
+	fi
 	exit;;
 -d|--download)
 	if download $emojisurl0 && download $emojisurl1
@@ -113,7 +137,7 @@ for vendor in `cat "$emojis0" |
 do	seli=`expr $seli + 1`
 	case "$vendor" in
 	Appl)	st=apple; apple=$seli;;
-	Goog)	st=google; google=$seli;;
+	Sample|Goog)	st=google; google=$seli;;
 	FB)	st=facebook; facebook=$seli;;
 	Wind)	st=windows; windows=$seli;;
 	Twtr)	st=twitter; twitter=$seli;;
@@ -124,7 +148,9 @@ do	seli=`expr $seli + 1`
 done
 
 case "$1" in
-"")	set - apple google facebook windows twitter emojione samsung;;
+"")	#set - apple google facebook windows twitter emojione samsung
+	set - google
+	;;
 esac
 sel=
 while	case "$1" in
@@ -142,7 +168,7 @@ do	sel="$sel$seli"
 	mkdir -p "$1"
 	shift
 done
-mkdir -p common
+mkdir -p common google
 
 export sel
 
@@ -179,6 +205,11 @@ img0 () {
   echo "$1" | base64 -d > common/$ename.png
 }
 
+imgg () {
+  echo " google $ename.png" >&2
+  echo "$1" | base64 -d > google/$ename.png
+}
+
 img () {
   style=$(( $style + 1 ))
   case $sel in
@@ -198,6 +229,7 @@ imgskip () {
 cat "$emojis0" "$emojis1" |
 sed -e "s/^.*name='\([^']*\)'.*U+.*/name \1/" -e "t name" \
     -e "s/.*—.*/imgskip/" -e t \
+    -e "s@^.*….*src='data:image/png;base64,\([^']*\)'.*src='data:image/png;base64,\([^']*\)'.*@imgg \1\nimg0 \2@" -e t \
     -e "s@^.*….*src='data:image/png;base64,\([^']*\)'.*@img0 \1@" -e t \
     -e "s@^.*src='data:image/png;base64,\([^']*\)'.*@img \1@" -e t \
     -e d \
